BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Raters" (
	"Name"	TEXT,
	"RaterID"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Ratings" (
	"Rating"	INTEGER,
	"RaterID"	INTEGER,
	"ShowID"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Shows" (
	"Show"	TEXT,
	"ShowID"	INTEGER
);
INSERT INTO "Raters" VALUES ('Laura',1);
INSERT INTO "Raters" VALUES ('Henry',2);
INSERT INTO "Raters" VALUES ('Paul',3);
INSERT INTO "Raters" VALUES ('Dan',4);
INSERT INTO "Raters" VALUES ('Marc',5);
INSERT INTO "Ratings" VALUES (3,1,1);
INSERT INTO "Ratings" VALUES (3,1,2);
INSERT INTO "Ratings" VALUES (5,1,3);
INSERT INTO "Ratings" VALUES (2,1,4);
INSERT INTO "Ratings" VALUES (3,1,5);
INSERT INTO "Ratings" VALUES (4,2,1);
INSERT INTO "Ratings" VALUES (3,2,2);
INSERT INTO "Ratings" VALUES (5,2,3);
INSERT INTO "Ratings" VALUES (NULL,2,4);
INSERT INTO "Ratings" VALUES (NULL,2,5);
INSERT INTO "Ratings" VALUES (4,3,1);
INSERT INTO "Ratings" VALUES (5,3,2);
INSERT INTO "Ratings" VALUES (3,3,3);
INSERT INTO "Ratings" VALUES (4,3,4);
INSERT INTO "Ratings" VALUES (NULL,3,5);
INSERT INTO "Ratings" VALUES (2,4,1);
INSERT INTO "Ratings" VALUES (3,4,2);
INSERT INTO "Ratings" VALUES (4,4,3);
INSERT INTO "Ratings" VALUES (3,4,4);
INSERT INTO "Ratings" VALUES (NULL,4,5);
INSERT INTO "Ratings" VALUES (4,5,1);
INSERT INTO "Ratings" VALUES (5,5,2);
INSERT INTO "Ratings" VALUES (5,5,3);
INSERT INTO "Ratings" VALUES (3,5,4);
INSERT INTO "Ratings" VALUES (3,5,5);
INSERT INTO "Shows" VALUES ('Reacher',1);
INSERT INTO "Shows" VALUES ('Silo',2);
INSERT INTO "Shows" VALUES ('Lasso',3);
INSERT INTO "Shows" VALUES ('Lioness',4);
INSERT INTO "Shows" VALUES ('Furious',5);
COMMIT;
